### ISSUE TITLE
Missing code for helpers_05_08 module.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jakevdp/PythonDataScienceHandbook#14]
Used in 05.08-Random-Forests, the code for ``helpers_05_08`` module needs to be included in the repo and either placed in the root directory so found when Jupyter notebook server started out of that directory, or made part of a Python package in a sub directory, which is then referenced by the ``requirements.txt`` file so that it will be installed by ``pip -r requirements.txt`` and made available when people running the notebook. Preferably people use a virtual environment given is module specific to your examples.

**Comment by jakevdp** [comment]
It is generated by running the appendix notebook.

When I finish putting all the content here, I'll make sure it's included in the repo.

**Comment by jakevdp** [comment]
Added now!
