### ISSUE TITLE
Use of non ASCII character in label in basemap example.

### ISSUE THREAD

**Issue by GrahamDumpleton** [jakevdp/PythonDataScienceHandbook#16]
In 04.13-Geographic-Data-With-Basemap you have the line:

```
plt.colorbar(label='temperature anomaly (°C)');
```

You may want to reconsider using the degrees symbol there as whether it will work may depend on unknown lang/locale settings in the environment.

```
UnicodeDecodeErrorTraceback (most recent call last)
<ipython-input-20-17334019f7eb> in <module>()
     10 
     11 plt.title('January 2014 Temperature Anomaly')
---> 12 plt.colorbar(label='temperature anomaly (°C)');
     13 #plt.colorbar(label='temperature anomaly (C)');

...

/opt/app-root/lib/python2.7/site-packages/matplotlib/colorbar.pyc in set_label(self, label, **kw)
    455         Label the long axis of the colorbar
    456         '''
--> 457         self._label = '%s' % (label, )
    458         self._labelkw = kw
    459         self._set_label()

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 21: ordinal not in range(128)
```

It is actually a bit strange as the lang/locale for the environment is UTF-8 and not ascii.

```
import locale
locale.getdefaultlocale()
Out[17]:
('en_US', 'UTF-8')
In [18]:

print(u'\u292e') 
⤮
In [21]:

print('temperature anomaly (°C)')
temperature anomaly (°C)
```

Not sure why ``matplotlib.pyplot`` is using ascii rather than default locale.

This is still with pinned versions of packages you had in ``requirements.txt`` so will try with latest of all packages and sees if that resolves anything.

**Comment by GrahamDumpleton** [comment]
This is only a problem with Python 2.7, not Python 3.5.

**Comment by jakevdp** [comment]
Thanks. The book is written with Python 3.

**Comment by GrahamDumpleton** [comment]
Your code looks to pretty portable though as initially I ran everything through Python 2.7 and that was the only thing that cropped up. Even then, it looks to be more of an limitation with ``matplotlib.pyplot`` on Python 2.
