### ISSUE TITLE
About Japanese translation

### ISSUE THREAD

**Issue by kozo2** [jakevdp/PythonDataScienceHandbook#17]
Hi @jakevdp 
Thank you for publishing these great notebooks.

I would like to translate your notebooks into Japanese (and publish it on GitHub).
But I am concerned that the translation is contrary to the ND (NoDerivatives).

I would like your comments on this CC-BY-NC-ND license issue.

**Comment by jakevdp** [comment]
Hi @kozo2 – thanks for your interest! Indeed, I believe that translations are not allowed by the ND clause. That said, I know that O'Reilly has done translations of other works – let me check with my contact there to see if there are any options.

**Comment by kozo2** [comment]
Thank you for your consideration.

**Comment by jakevdp** [comment]
Hi @kozo2 – it sounds like any translation of this content will need to go through O'Reilly. You can contact Helen Monroe if you're interested in pursuing this; it's Helen (at) oreilly.co.uk

**Comment by kozo2** [comment]
FYI, I received an E-mail from O'Reilly Japan that this attempt is unacceptable.
