### ISSUE TITLE
Something is odd in digits-classification plot

### ISSUE THREAD

**Issue by bwinkel** [jakevdp/PythonDataScienceHandbook#18]
There seems to be an error in the last plot (line 32) of `05.02-Introducing-Scikit-Learn.ipynb` (digits classification example). The green labels are not matching those in the figure in line 23.

**Comment by jakevdp** [comment]
Good eye – thanks for pointing that out! The plot should show the test points rather than the training points. I'll try to push a fix tonight.

**Comment by jakevdp** [comment]
Fixed in e912ac11209db796f3c0d4b3a91d6c622c2756b8. Thanks!
