### ISSUE TITLE
Instructions to create PDSH conda environment fails

### ISSUE THREAD

**Issue by dwelden** [jakevdp/PythonDataScienceHandbook#19]
Fetching package metadata .........
Solving package specifications: ....

UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy ==1.11
  - python 3.5*
Use "conda info <package>" to see the dependencies for each package.

**Comment by jakevdp** [comment]
What operating system are you on?

**Comment by dwelden** [comment]
Windows 7 Enterprise Service Pack 1 (Version 6.1.7601). Conda version 4.2.13.

**Comment by jakevdp** [comment]
Huh. It might be that numpy 1.11 builds are not available for Windows on conda. I'd suggest using numpy 1.10 instead.

**Comment by jakevdp** [comment]
If this continues to be an issue, I'd ask for help on the conda mailing list.

**Comment by jakevdp** [comment]
I changed the requirement to 1.11.1 – you might check if that works better. I don't have access to a Windows machine, so all I can do is take shots in the dark here...

If you come up with a good solution please let me know.

**Comment by dwelden** [comment]
Fails under Linux Mint 18 32-bit with Conda v4.2.13 also. Different UnsatisfiableError this time though:

`dave@dave-VirtualBox ~ $ conda create -n PDSH python=3.5 --file PDSHrequirements.txt
Fetching package metadata .......
Solving package specifications: ....


UnsatisfiableError: The following specifications were found to be in conflict:
  - basemap -> numpy 1.10*|1.7*|1.8*|1.9*
  - basemap -> python 2.6*|3.3*
  - numpy ==1.11.1
Use "conda info <package>" to see the dependencies for each package.
`

**Comment by jakevdp** [comment]
What if you try with ``--channel conda-forge``?

**Comment by jakevdp** [comment]
I think the best fix might be to remove the requirements file entirely, and go back to just listing dependencies in the README. It's less convenient, but I'm not certain it's possible to fix this so that it will work perfectly for everyone.

**Comment by dwelden** [comment]
Oddly enough, mixed results: on my Windows 64 system, the PDSH environment is installing as I type. On the linux system, same error as before. If the Windows environment is operational when it completes, I will abandon the linux environment and proceed. Either way, I will post at least one more time with the results.

Thanks for your patient assistance.
