### ISSUE TITLE
Figure 5-32

### ISSUE THREAD

**Issue by vahndi** [jakevdp/PythonDataScienceHandbook#2]
Hi Jake, awesome book, it's actually taught me a lot that I didn't know about matplotlib and numpy. I'm glad you've covered all the core technologies that we use as Python data scientists, not just machine learning.
One observation of Figure 5-32 on page 374 - it looks like the training and validation curves are the wrong way around. Is this right?

**Comment by jakevdp** [comment]
Yep, I fixed that recently, but the changes haven't made that here yet.
