### ISSUE TITLE
Numpy not importing in the environment

### ISSUE THREAD

**Issue by kamal-hothi** [jakevdp/PythonDataScienceHandbook#21]
On MacOS(Sierra) with other Conda environments succeeding in importing numpy, PDSH environment fails, with the following error -

`ImportError: dlopen(//anaconda/envs/PDSH/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libopenblas-r0.2.18.dylib
  Referenced from: //anaconda/envs/PDSH/lib/python3.5/site-packages/numpy/core/multiarray.cpython-35m-darwin.so
  Reason: image not found`

**Comment by jakevdp** [comment]
It is probably an issue with library paths on your system. The conda mailing list would probably be the best place to get help with this.

**Comment by kamal-hothi** [comment]
Thanks and sorry for posting unnecessarily.
