### ISSUE TITLE
03.10-Working-With-Strings - JSON lines

### ISSUE THREAD

**Issue by evrial** [jakevdp/PythonDataScienceHandbook#25]
Since pandas 0.19 there is a boolean argument [`lines`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_json.html#pandas.read_json) exactly for this case. Probably worth to mention. Also pandas can work perfectly with compressed files locally (hopefully in the next version remotely too).

**Comment by jakevdp** [comment]
Thanks! I'll keep that in mind for the next edition.

**Comment by evrial** [comment]
Ok, thanks for your excellent book!

**Comment by evrial** [comment]
Forgot one more thing — Shift+Tab shortcut is super useful in notebook editor, good to note that too.
