### ISSUE TITLE
Typo in 04.02-Simple-Scatter-Plots? 

### ISSUE THREAD

**Issue by liamcoatman** [jakevdp/PythonDataScienceHandbook#27]
> Notice that the size of points is given in pixels, the color argument is automatically mapped to a color scale (shown here by the colorbar() command), and that the size argument is given in pixels. 

"Given in pixels" repeated twice?

**Comment by jakevdp** [comment]
Thanks! fixed in https://github.com/jakevdp/PythonDataScienceHandbook/commit/608a30f0e4b83c8b2259e3e50f67d37c1d88f6c5
