### ISSUE TITLE
Change deprecated Set operations on pd.Index

### ISSUE THREAD

**Issue by milodubois** [jakevdp/PythonDataScienceHandbook#349]
Future versions of Pandas will not support `pd.Index` operations like this:

```py
first | second
```

but must be used like this

```py
first.union(second)
```

This is similar for `&` and `^`.

See merged [PR #37374](https://github.com/pandas-dev/pandas/pull/37374) in pandas-dev/pandas.

Thus, all references, including the introductory reference in chapter 03.01 should be updated in PDSH or perhaps users should be made aware of this change when going through PDSH.

Thank you.

**Comment by jakevdp** [comment]
Thanks – see https://www.oreilly.com/library/view/python-data-science/9781098121211/; I'll update the notebooks here soon.
