### ISSUE TITLE
correction to inches calculation in 02.06-Boolean-Arrays-and-Masks

### ISSUE THREAD

**Issue by koalabearski** [jakevdp/PythonDataScienceHandbook#36]
I wasn't able to recreate a little part of this notebook's output.  It seemed that dividing rainfall by 254 made the numbers too small.  

May I propose rerunning it with the change below? 

Line 6 in Input 1
(-)  inches = rainfall / 254  # 1/10mm -> inches
(+) inches = rainfall / 25.4  # 1/10mm -> inches

This makes the numbers on a scale that show up in the plot.  

It does mean changing the number reported between cells 23 and 24.  It'll also affect the output once rerun of 23, 24, 25, and 29 though I think it doesn't change the meaning of those examples.  I'd have done this through a pull request, but notebooks in github are an unfamiliar beast to me for now.

**Comment by jakevdp** [comment]
Thanks for the note. I guess I'm a bit confused... are you saying the data source has changed somehow?

**Comment by koalabearski** [comment]
I'm not confident in my answer, but I think the data has changed.  It appears to be in mm now - I like how you put it in increasing scale, I was getting lost thinking about it!.  

What's more, the numbers themselves may have changed since even when it's scaled to show up on the plot and fit the array masks properly, it doesn't give the same answers as if it had just been a change of scale.

**Comment by koalabearski** [comment]
Ah, I should have also changed the note from 1/10mm to mm so it would now be:

(-) inches = rainfall / 254 # 1/10mm -> inches
(+) inches = rainfall / 25.4 # mm -> inches

**Comment by koalabearski** [comment]
If I'm right, then I should have also changed:

(-) # 1/10mm -> inches
(+) # mm -> inches

**Comment by jakevdp** [comment]
Hi,
The issue here is that integer division in Python 2 is floor division, so this calculation rounds to zero in Python 2. To fix it, upgrade to Python 3 (or change ``254`` to ``254.0``, but I'd highly suggest upgrading to Python 3 unless you have a very good reason to stay on Python 2).
