### ISSUE TITLE
conda environment creation using the txt file. basemap depends on Python2.7. Gives an UnsatisfiableError

### ISSUE THREAD

**Issue by WildYorkies** [jakevdp/PythonDataScienceHandbook#44]
The specifications were found to be in conflict:
- basemap -> python 2.7*
- python 3.5*

**Comment by WildYorkies** [comment]
Deleted basemap from requirements.txt and everything installed fine.

Now I just need to figure out how to install basemap for python 3.5

**Comment by jakevdp** [comment]
If basemap is not available on 3.5 for your operating system, you might try installing via conda-forge.
