### ISSUE TITLE
max margin example: magic numbers?

### ISSUE THREAD

**Issue by amueller** [jakevdp/PythonDataScienceHandbook#56]
Hey jake. I'm about to steal your max margin example for my lecture.
It looks like there are [magic numbers](https://render.githubusercontent.com/view/ipynb?commit=c628cd22b1d82766824a1ad4647e6e33a61974f1&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f6a616b657664702f507974686f6e44617461536369656e636548616e64626f6f6b2f633632386364323262316438323736363832346131616434363437653665333361363139373466312f6e6f7465626f6f6b732f30352e30372d537570706f72742d566563746f722d4d616368696e65732e6970796e62&nwo=jakevdp%2FPythonDataScienceHandbook&path=notebooks%2F05.07-Support-Vector-Machines.ipynb&repository_id=65388917#Support-Vector-Machines:-Maximizing-the-Margin)
 that show the margin of the other candidates.

Where do they come from? eyeballing?

Also, I feel like we might put that into the sklearn example gallery?

**Comment by jakevdp** [comment]
Yep, I think I just eyeballed those.

**Comment by jakevdp** [comment]
As far as putting in sklearn... the code is MIT licensed and can be copied. But the discussion has a more restrictive license and probably cannot.

That said, I have an older BSD-licensed version of a similar thing in http://github.com/jakevdp/sklearn_tutorial

**Comment by amueller** [comment]
Cool :)
I we can write a new discussion relatively easily after stealing the code ;)
