### ISSUE TITLE
Question: porting Ruby language (and publishing it on GitHub)

### ISSUE THREAD

**Issue by kozo2** [jakevdp/PythonDataScienceHandbook#59]
I would like to port PythonDataScienceHandbook to Ruby programming language (at the first in Japanese for the text).
At the moment the Ruby datascience environment is immature and can not be a complete port, but I would like to borrow the dataset and the text outline.
Is this attempt contrary to your PythonDataScienceHandbook license terms?

**Comment by jakevdp** [comment]
Any translation or derived work would have to go through OReilly. Let me know if you'd like me to get you in touch with the right person.

**Comment by kozo2** [comment]
Thank you for your reply.
I know the OReilly (Japanese) person for this.
I will send an e-mail to the person.

**Comment by kozo2** [comment]
FYI, I received an E-mail from O'Reilly Japan that this attempt is unacceptable.
