### ISSUE TITLE
Typo in 02.06-Boolean-Arrays-and-Masks

### ISSUE THREAD

**Issue by funwalla** [jakevdp/PythonDataScienceHandbook#63]
The Boolean Operators section of 02.06-Boolean-Arrays-and-Masks.ipynb includes the phrase:
"the equivalence of A AND B and NOT (A OR B)".

I believe that should be: "the equivalence of A AND B and NOT (NOT A OR NOT B)". That is what is shown in the code fragment below the markdown: np.sum(~( (inches <= 0.5) | (inches >= 1) )).

**Comment by jakevdp** [comment]
Thanks! Fixed in b498e1c4bd56af22660636fc276b4a7a6689bfde
