### ISSUE TITLE
Example: Recipe Database - !gunzip command not working  

### ISSUE THREAD

**Issue by marco-vene** [jakevdp/PythonDataScienceHandbook#67]
Hi,

I am trying to reproduce the code at page 184 of the book (Chapter 3).

# !curl -O http://openrecipes.s3.amazonaws.com/recipeitems-latest.json.gz
# !gunzip recipeitems-latest.json.gz

the second command to unzip the file gives me the error:
'gunzip' is not recognized as an internal or external command,
operable program or batch file.

How can I unzip the file?
Thanks,

Marco

**Comment by marco-vene** [comment]
Actually I just saw the adderss: http://openrecipes.s3.amazonaws.com/recipeitems-latest.json.gz does not contain the correct file.

**Comment by jakevdp** [comment]
Yes, it seems that the original file was removed.

**Comment by jakevdp** [comment]
See

**Comment by MLShooter** [comment]
https://github.com/sameergarg/scala-elasticsearch/blob/master/conf/recipeitems-latest.json.gz

**Comment by Vic-ade** [comment]
thanks @wulj2

**Comment by tuananh0622** [comment]
thank you! @wulj2
