### ISSUE TITLE
Bicycle analysis: Spike in west-side traffic missing in avaiable dataset

### ISSUE THREAD

**Issue by AllanLRH** [jakevdp/PythonDataScienceHandbook#69]
The dataset appears to have been updated?

Downloaded using `curl -o FremontBridge.csv https://data.seattle.gov/api/views/65db-xm6k/rows.csv?accessType=DOWNLOAD`

The plot in the notebook:
![havespike](https://cloud.githubusercontent.com/assets/2641327/24861970/fdd83b9c-1dfa-11e7-8ce2-a09a2b9c3af6.png)

My plot, without the blue spike:
![missingspikes](https://cloud.githubusercontent.com/assets/2641327/24861975/05b11a96-1dfb-11e7-981e-828cf98dbc8c.png)

[Relevant notebook](http://nbviewer.jupyter.org/github/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/03.11-Working-with-Time-Series.ipynb) (from input cell 40).

**Comment by jakevdp** [comment]
Yes, the dataset is continually updated, and I've found that at any given point [the most recent data is probably suspect](https://twitter.com/jakevdp/status/656573200864706561)
