### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by fbs82** [jakevdp/PythonDataScienceHandbook#71]
Some of the Scikit modules/classes trigger deprecation warnings. 
1.  The contents of the `cross_validation` submodule will be moved to  `model_selection`.
2. `GaussianMixure` will replace `GMM`.

**Comment by jakevdp** [comment]
Thanks! I'm aware of these, but the version requirements are stated pretty clearly in the repository. I'll upgrade package versions if there's ever a second edition.
