### ISSUE TITLE
Can not install basemap via pip anymore

### ISSUE THREAD

**Issue by yuvipanda** [jakevdp/PythonDataScienceHandbook#72]
Due to https://github.com/matplotlib/basemap/issues/251, pip can no longer install basemap like it is specified in requirements.txt

**Comment by jakevdp** [comment]
Ok - thanks for letting me know. I'd suggest installing via conda - that should still work.

**Comment by fbs82** [comment]
On Windows the standard basemap package doesn't work with Python 3. One can use the conda-forge version instead: https://anaconda.org/conda-forge/basemap

**Comment by johanovic** [comment]
Could the notebooks run without basemap? Many people don't use conda, but use pip and venvs only. Thanks

**Comment by jakevdp** [comment]
Only one of the notebooks uses basemap. I think it might be best to just remove the requirement because of all the trouble it's causing.

**Comment by jakevdp** [comment]
Basemap is no longer in requirements: https://github.com/jakevdp/PythonDataScienceHandbook/commit/475499f1464bcdf96e618c922a8e6c92b190ee9a

**Comment by yuvipanda** [comment]
This makes the repo work with beta binder now:

https://beta.mybinder.org/v2/gh/jakevdp/PythonDataScienceHandbook/master

Thanks for the fix!
