### ISSUE TITLE
Request for .pdf .epub .mobi formats?

### ISSUE THREAD

**Issue by dandanio** [jakevdp/PythonDataScienceHandbook#85]
Hey Jake,

I would appreciate if you could at least consider releasing the book as a .pdf, .epub or .mobi as a great tool to add to my portable/commute/trip library on the tablet or the phone. I think the pros way outweigh the cons and it would be an awesome addition to any programmer's or scientist's workshop.

Btw. Congrats on an awesome book!

**Comment by jakevdp** [comment]
Hi @dandanio – for those kinds of formats, you might check out O'Reilly's Safari subscription service. It gives you access to various e-book formats for this book and others. I don't have plans to make any of those available for free at this time.

**Comment by dandanio** [comment]
Understood! :) Thanks for a quick response! :+1:
